Anzahl_Fotos= int(input("Wie viele Bilder ?: "))
Größe= int(input("Größe eingeben: "))
Breite= int(input("Breite eingen: "))
Farbtiefe_RGB=["rot","grün","gelb"]

print("\n")
print("Rechnung wird durchgeführt....")
print("Pixelanzahl pro Bild","=", Größe ,"x" ,Breite,"Pixel")
Rechnung1=(round(Größe*Breite,6))
print(Rechnung1," Pixel/Bild")
print("\n")
print("Byte pro Pixel","=","(Anzahl Farbtiefe x Bit pro Farbkanal)/8")
print("(",len(Farbtiefe_RGB),"x 8 Bit/Pixel)/8 Bit/Pixel")
Rechnung2=(len(Farbtiefe_RGB)*8/8)
print(Rechnung2,"Byte/Pixel")
print("\n")
print("Speicherbedarf pro Bild = ",Rechnung1,"Pixel/Bild", "x 3 Byte/Pixel")
Rechnung3=(Rechnung1*3)
print(Rechnung3 , "Byte/Bild")
print("\n")
Rechnung4=(Rechnung3*Anzahl_Fotos)
print("Speicherbedarf gesamt beträgt = ",Rechnung3,"Byte/Bild x",Anzahl_Fotos,"Bilder","=",Rechnung4," Byte")
Rechnung5=(Rechnung4/1024)
print(Rechnung4,"Byte / 1024 =",Rechnung5,"KiB / 1024")
Rechnung6=round((Rechnung5/1024),2)
print(round(Rechnung6,2),"MiB /1024")
print(round(Rechnung6/1024/10,2),"Gib")